<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="inail2_torso" params="rot parent *origin">
        <!-- base -->
        <link name="torso">
            <inertial>
                <origin xyz="${Torso_x} ${rot*Torso_y} ${Torso_z}" />
                <mass value="${Torso_mass}" />
                <inertia ixx="${Torso_xx}" ixy="${rot*Torso_xy}" ixz="${Torso_xz}" iyy="${Torso_yy}"
                    iyz="${rot*Torso_yz}" izz="${Torso_zz}" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://inail2upperbody_urdf/meshes/inail_torso.stl"
                        scale="0.001 ${rot*0.001} 0.001" />
                </geometry>
                <material name="dark_grey" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://inail2upperbody_urdf/meshes/simple/inail_torso.stl"
                        scale="0.001 ${rot*0.001} 0.001" />
                </geometry>
            </collision>
        </link>
        <!-- base -->

        <joint name="base_joint" type="fixed">
            <parent link="${parent}" />
            <child link="torso" />
            <xacro:insert_block name="origin" />
        </joint>


    </xacro:macro>

</robot>
